Repository ck2plus/CK2Plus_Rewrite, pull requests merged in 2019-11, with the labels that each got.

#69 Culture/szekely
  CK2Plus_expanded/history/provinces/1639 - Bacau.txt
  CK2Plus_expanded/history/provinces/445 - Pressburg.txt
  CK2Plus_expanded/history/provinces/450 - Sopron.txt
  CK2Plus_expanded/history/provinces/454 - Vas.txt
  CK2Plus_expanded/history/provinces/540 - Szekelyfold.txt
Labels: enhancement

#70 Cultures/caucasian
  CK2Plus_expanded/history/provinces/1805 - Balanjar.txt
  CK2Plus_expanded/history/provinces/1806 - Egrisi.txt
  CK2Plus_expanded/history/provinces/598 - Tmutarakan.txt
  CK2Plus_expanded/history/provinces/599 - Kuban.txt
  CK2Plus_expanded/history/provinces/600 - Abkhazia.txt
  CK2Plus_expanded/history/provinces/602 - Kasogs.txt
  CK2Plus_expanded/history/provinces/673 - Albania.txt
  CK2Plus_expanded/history/provinces/674 - Derbent.txt
  CK2Plus_expanded/history/provinces/676 - Kakheti.txt
Labels: enhancement

#71 Cultures/southern italy
  CK2Plus_expanded/history/provinces/1577 - Cinarca.txt
  CK2Plus_expanded/history/provinces/1707 - Chieti.txt
  CK2Plus_expanded/history/provinces/1712 - Catanzaro.txt
  CK2Plus_expanded/history/provinces/1890 - Corfu.txt
  CK2Plus_expanded/history/provinces/324 - Corsica.txt
  CK2Plus_expanded/history/provinces/334 - Napoli.txt
  CK2Plus_expanded/history/provinces/335 - Benevento.txt
  CK2Plus_expanded/history/provinces/336 - Salerno.txt
  CK2Plus_expanded/history/provinces/337 - Consenza.txt
  CK2Plus_expanded/history/provinces/338 - Reggio.txt
  CK2Plus_expanded/history/provinces/340 - Palermo.txt
  CK2Plus_expanded/history/provinces/344 - Taranto.txt
  CK2Plus_expanded/history/provinces/345 - Lecce.txt
  CK2Plus_expanded/history/provinces/346 - Bari.txt
  CK2Plus_expanded/history/provinces/347 - Apulia.txt
  CK2Plus_expanded/history/provinces/348 - Foggia.txt
  CK2Plus_expanded/history/provinces/474 - Cephalonia.txt
  CK2Plus_expanded/history/provinces/851 - Capua.txt
  CK2Plus_expanded/history/provinces/935 - Amalfi.txt
Labels: enhancement

#76 Cultures/balkans
  CK2Plus_expanded/history/provinces/1887 - Lyncestis.txt
  CK2Plus_expanded/history/provinces/1888 - Astibus.txt
  CK2Plus_expanded/history/provinces/1971 - Bilino Polje.txt
  CK2Plus_expanded/history/provinces/459 - Veglia.txt
  CK2Plus_expanded/history/provinces/465 - Zadar.txt
  CK2Plus_expanded/history/provinces/466 - Zachlumia.txt
  CK2Plus_expanded/history/provinces/467 - Split.txt
  CK2Plus_expanded/history/provinces/468 - Ragusa.txt
  CK2Plus_expanded/history/provinces/471 - Ochrid.txt
Labels: enhancement

#77 Titles/title requirements
  CK2Plus/common/scripted_triggers/000_CK2Plus_title_requirements.txt
  CK2Plus_expanded/common/landed_titles/landed_titles.txt
  CK2Plus_expanded/history/titles/k_franconia_otto.txt
  CK2Plus_expanded/history/titles/k_swabia_otto.txt
  CK2Plus_expanded/history/titles/k_thuringia_otto.txt
Labels: enhancement

#80 Cultures/galician
  CK2Plus_expanded/common/cultures/000_CK2Plus_iberian.txt
  CK2Plus_expanded/history/provinces/156 - Coruna.txt
  CK2Plus_expanded/history/provinces/157 - Santiago.txt
  CK2Plus_expanded/history/provinces/158 - Porto.txt
  CK2Plus_expanded/history/provinces/159 - Coimbra.txt
  CK2Plus_expanded/history/provinces/187 - Castelo Branco.txt
  CK2Plus_expanded/history/provinces/188 - Braganza.txt
  CK2Plus_expanded/history/provinces/1976 - Lugo.txt
  CK2Plus_expanded/history/provinces/2012 - Egitanea.txt
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_cultures.csv
Labels: enhancement

#83 kutama -> sanhaja; fix a couple dynasties and add a couple more
  CK2Plus_expanded/common/cultures/000_CK2Plus_amazigh.txt
  CK2Plus_expanded/common/dynasties/00_dynasties.txt
  CK2Plus_expanded/history/provinces/1727 - Arigh.txt
  CK2Plus_expanded/history/provinces/1728 - Tebessa.txt
  CK2Plus_expanded/history/provinces/1729 - Tuggurt.txt
  CK2Plus_expanded/history/provinces/815 - Kairwan.txt
  CK2Plus_expanded/history/provinces/816 - Mahdia.txt
  CK2Plus_expanded/history/provinces/818 - Medjerda.txt
  CK2Plus_expanded/history/provinces/821 - Constantine.txt
  CK2Plus_expanded/history/provinces/823 - Biskra.txt
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_cultures.csv
Labels: enhancement

#84 Cultures/egypt
  CK2Plus_expanded/history/provinces/1468 - Fayoum.txt
  CK2Plus_expanded/history/provinces/1781 - al-Qusair.txt
  CK2Plus_expanded/history/provinces/2001 - Faiyum.txt
  CK2Plus_expanded/history/provinces/2002 - Akhmim.txt
  CK2Plus_expanded/history/provinces/2003 - Esna.txt
  CK2Plus_expanded/history/provinces/2004 - Kharibta.txt
  CK2Plus_expanded/history/provinces/2005 - Paraetonium.txt
  CK2Plus_expanded/history/provinces/2006 - Kolzum.txt
  CK2Plus_expanded/history/provinces/2007 - Farafra.txt
  CK2Plus_expanded/history/provinces/788 - Farama.txt
  CK2Plus_expanded/history/provinces/789 - Pelusia.txt
  CK2Plus_expanded/history/provinces/790 - Sarqihya.txt
  CK2Plus_expanded/history/provinces/791 - Quena.txt
  CK2Plus_expanded/history/provinces/794 - Aswan.txt
  CK2Plus_expanded/history/provinces/795 - Asyut.txt
  CK2Plus_expanded/history/provinces/796 - Cairo.txt
  CK2Plus_expanded/history/provinces/797 - Manupura.txt
  CK2Plus_expanded/history/provinces/798 - Delta.txt
  CK2Plus_expanded/history/provinces/799 - Gabiyaha.txt
  CK2Plus_expanded/history/provinces/800 - Gizeh.txt
  CK2Plus_expanded/history/provinces/801 - Buhairya.txt
  CK2Plus_expanded/history/provinces/802 - Alexandria.txt
  CK2Plus_expanded/history/provinces/803 - Quattara.txt
  CK2Plus_expanded/history/provinces/803 - Sewa.txt
  CK2Plus_expanded/history/provinces/804 - Al Alamayn.txt
Labels: enhancement

#89 small changes
  CK2Plus_expanded/history/provinces/1727 - Arigh.txt
  CK2Plus_expanded/history/provinces/1728 - Tebessa.txt
  CK2Plus_expanded/history/provinces/1729 - Tuggurt.txt
  CK2Plus_expanded/history/provinces/1734 - Ashir.txt
  CK2Plus_expanded/history/provinces/823 - Biskra.txt
  CK2Plus_expanded/history/provinces/828 - Ouled Nail.txt
Labels: enhancement

#92 fix bad celtic priest localisation
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_traits.csv
Labels: bug

#91 Cultures/west central africa
  CK2Plus_expanded/history/provinces/1761 - Bure.txt
  CK2Plus_expanded/history/provinces/1762 - Tagant.txt
  CK2Plus_expanded/history/provinces/1764 - Diafunu.txt
  CK2Plus_expanded/history/provinces/1765 - Kantor.txt
  CK2Plus_expanded/history/provinces/1771 - Ennedi.txt
  CK2Plus_expanded/history/provinces/912 - Aoudaghost.txt
  CK2Plus_expanded/history/provinces/926 - Bambuk.txt
Labels: enhancement

#95 oxford comma
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_religions.csv
Labels: bug

#93 add localisation for szekely
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_cultures.csv
Labels: bug

#98 added missed stuff
  CK2Plus_expanded/history/provinces/1883 - Kastoria.txt
  CK2Plus_expanded/history/provinces/339 - Messina.txt
  CK2Plus_expanded/history/provinces/446 - Morava.txt
  CK2Plus_expanded/history/provinces/745 - Smyrna.txt
Labels: enhancement

#101 siculo-greek --> griko
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_cultures.csv
Labels: enhancement

#100 replace colon with semicolon
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_cultures.csv
Labels: bug

#103 add gitattributes
  .gitattributes
Labels: bug, enhancement

#105 Fix/some validator fixes
  CK2Plus_expanded/common/cultures/000_CK2Plus_aramaic.txt
  CK2Plus_expanded/common/cultures/000_CK2Plus_northeast_caucasian.txt
  CK2Plus_expanded/common/cultures/000_CK2Plus_northwest_caucasian.txt
  CK2Plus_expanded/common/cultures/000_CK2Plus_turkic.txt
  CK2Plus_expanded/history/provinces/1115 - Cholamandalam.txt
  CK2Plus_expanded/history/provinces/159 - Coimbra.txt
  CK2Plus_expanded/history/provinces/187 - Castelo Branco.txt
  CK2Plus_expanded/history/provinces/188 - Braganza.txt
  CK2Plus_expanded/history/provinces/2003 - Esna.txt
  CK2Plus_expanded/history/provinces/290 - Uppland.txt
  CK2Plus_expanded/history/provinces/333 - Roma.txt
  CK2Plus_expanded/history/provinces/340 - Palermo.txt
  CK2Plus_expanded/history/provinces/405 - Chud.txt
  CK2Plus_expanded/history/provinces/413 - Pskov.txt
  CK2Plus_expanded/history/provinces/536 - Galich.txt
  CK2Plus_expanded/history/provinces/551 - Mstislavl.txt
  CK2Plus_expanded/history/provinces/582 - Vladimir.txt
  CK2Plus_expanded/history/provinces/586 - Galich Mersky.txt
  CK2Plus_expanded/history/provinces/592 - Burtasy.txt
  CK2Plus_expanded/history/provinces/709 - Asas.txt
  CK2Plus_expanded/history/provinces/747 - Lykia.txt
  CK2Plus_expanded/history/titles/d_asturias.txt
  CK2Plus_expanded/history/titles/d_deheubarth.txt
  CK2Plus_expanded/history/titles/d_gurjara_mandala.txt
  CK2Plus_expanded/history/titles/d_holland.txt
  CK2Plus_expanded/history/titles/d_ikh_bogd.txt
  CK2Plus_expanded/history/titles/d_karashar.txt
  CK2Plus_expanded/history/titles/d_kartli.txt
  CK2Plus_expanded/history/titles/d_scholae_palatinae.txt
  CK2Plus_expanded/history/titles/d_zavarot.txt
  CK2Plus_expanded/localisation/000_ck2Plus_expanded_titles.csv
Labels: bug

#107 Fix/some validator fixes
  CK2Plus_expanded/history/provinces/1468 - Fayoum.txt
  CK2Plus_expanded/history/provinces/1634 - Novosil.txt
  CK2Plus_expanded/history/provinces/1636 - Zvenyhorod.txt
  CK2Plus_expanded/history/provinces/1650 - Vorotynsk.txt
  CK2Plus_expanded/history/provinces/1652 - Borovichi.txt
  CK2Plus_expanded/history/provinces/1659 - Drutsk.txt
  CK2Plus_expanded/history/provinces/1664 - Tikhvine.txt
  CK2Plus_expanded/history/provinces/1665 - Yelets.txt
  CK2Plus_expanded/history/provinces/1666 - Karachev.txt
  CK2Plus_expanded/history/provinces/1671 - Rylsk.txt
  CK2Plus_expanded/history/provinces/1675 - Priluk.txt
  CK2Plus_expanded/history/provinces/1676 - Kromy.txt
  CK2Plus_expanded/history/provinces/1681 - Kursk.txt
  CK2Plus_expanded/history/provinces/1682 - Kozelsk.txt
  CK2Plus_expanded/history/provinces/446 - Morava.txt
  CK2Plus_expanded/history/provinces/803 - Sewa.txt
  CK2Plus_expanded/history/provinces/854 - Zamindawar.txt
  CK2Plus_expanded/history/titles/d_kabul.txt
  CK2Plus_expanded/history/titles/d_leon.txt
  CK2Plus_expanded/history/titles/d_munster.txt
  CK2Plus_expanded/history/titles/d_nestorian.txt
  CK2Plus_expanded/history/titles/d_ngari.txt
  CK2Plus_expanded/history/titles/d_pechora.txt
  CK2Plus_expanded/history/titles/d_smolensk.txt
Labels: bug

#110 gitattributes simplification
  .gitattributes
Labels: bug

#112 remove trait from its own opposites
  CK2Plus_expanded/common/traits/000_CK2Plus_expanded_traits.txt
Labels: bug

#116 move extra houara dynasties into their own file
  CK2Plus_expanded/common/dynasties/000_CK2Plus_houara.txt
  CK2Plus_expanded/common/dynasties/00_CK2Plus_ranges.txt
  CK2Plus_expanded/common/dynasties/00_dynasties.txt
Labels: enhancement

#118 Fix/more validator fixes
  CK2Plus_expanded/history/provinces/1707 - Chieti.txt
  CK2Plus_expanded/history/provinces/187 - Castelo Branco.txt
  CK2Plus_expanded/history/provinces/1975 - Palencia.txt
  CK2Plus_expanded/history/provinces/199 - Burgos.txt
  CK2Plus_expanded/history/provinces/275 - Nidaros.txt
  CK2Plus_expanded/history/provinces/338 - Reggio.txt
  CK2Plus_expanded/history/provinces/583 - Suzdal.txt
  CK2Plus_expanded/history/provinces/791 - Quena.txt
  CK2Plus_expanded/history/provinces/794 - Aswan.txt
  CK2Plus_expanded/history/provinces/799 - Gabiyaha.txt
Labels: bug

#122 Fix/duplicate dynasties
  CK2Plus_expanded/common/dynasties/00_dynasties.txt
  CK2Plus_expanded/history/characters/breton.txt
  CK2Plus_expanded/history/characters/german.txt
  CK2Plus_expanded/history/characters/lombard.txt
  CK2Plus_expanded/history/characters/maghreb_arabic.txt
  CK2Plus_expanded/history/characters/persian.txt
Labels: bug

#120 Empire Breakup Mechanic
  CK2Plus/common/on_actions/000_CK2Plus_on_actions.txt
  CK2Plus/common/scripted_triggers/000_CK2Plus_title_requirements.txt
  CK2Plus/events/000_CK2Plus_empire_breakup.txt
Labels: enhancement

#130 Cultures/anatolian dynasties.changed
  CK2Plus_expanded/common/dynasties/000_CK2Plus_anatolian.txt
  CK2Plus_expanded/common/dynasties/000_CK2Plus_oghuz.txt
  CK2Plus_expanded/common/dynasties/000_CK2Plus_turkish.txt
  CK2Plus_expanded/common/dynasties/00_CK2Plus_ranges.txt
Labels: enhancement

#134 Laws/fixes
  CK2Plus_expanded/common/laws/000_CK2Plus_council_power_laws.txt
  CK2Plus_expanded/common/laws/000_CK2Plus_crown_laws.txt
  CK2Plus_expanded/common/laws/000_CK2Plus_gender_laws.txt
  CK2Plus_expanded/common/laws/000_CK2Plus_obligation_laws.txt
  CK2Plus_expanded/common/laws/000_CK2Plus_realm_laws.txt
  CK2Plus_expanded/common/laws/000_CK2Plus_succession_laws.txt
Labels: bug, enhancement

#136 Government Trigger Simplification
  CK2Plus/common/governments/000_CK2Plus_feudal_governments.txt
  CK2Plus/common/governments/_governments.info
  CK2Plus/common/governments/feudal_governments.txt
  CK2Plus/common/governments/nomadic_governments.txt
  CK2Plus/common/governments/republic_governments.txt
  CK2Plus/common/governments/theocracy_governments.txt
  CK2Plus/common/governments/tribal_governments.txt
  CK2Plus/gfx/interface/governments/government_icon_mercenary.dds
  CK2Plus/interface/CK2Plus_governments.gfx
  CK2Plus/localisation/000_CK2Plus_governments.csv
Labels: CAUTION, enhancement

#135 Feature/hixtoryfix byzantium
  CK2Plus_expanded/history/characters/000_CK2Plus_expanded_roman.txt
  CK2Plus_expanded/history/characters/00_naming.info
  CK2Plus_expanded/history/characters/greek.txt
  CK2Plus_expanded/history/characters/roman.txt
  CK2Plus_expanded/history/titles/e_byzantium.txt
  CK2Plus_expanded/history/titles/e_roman_empire.txt
  CK2Plus_expanded/history/titles/k_hellenic_pagan.txt
Labels: enhancement

#139 Feature/cultural localization
  CK2Plus/localisation/000_CK2Plus_title_holders.csv
  CK2Plus/localisation/000_CK2Plus_title_holders_culture_groups.csv
  CK2Plus/localisation/000_CK2Plus_title_holders_cultures.csv
  CK2Plus/localisation/000_CK2Plus_title_holders_religion.csv
  CK2Plus/localisation/000_CK2Plus_title_types.csv
  CK2Plus/localisation/000_CK2Plus_title_types_culture_groups.csv
  CK2Plus/localisation/000_CK2Plus_title_types_cultures.csv
  CK2Plus/localisation/000_CK2Plus_title_types_religion.csv
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_religions.csv
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_title_holders_religion.csv
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_title_types_religion.csv
Labels: enhancement

#138 Fix/localization
  CK2Plus/events/000_CK2Plus_empire_breakup.txt
  CK2Plus/localisation/000_CK2Plus_ambitions.csv
  CK2Plus/localisation/000_CK2Plus_custom_modifiers.csv
  CK2Plus/localisation/000_CK2Plus_custom_tooltips.csv
  CK2Plus/localisation/000_CK2Plus_empire_events.csv
  CK2Plus/localisation/000_CK2Plus_event_modifiers.csv
  CK2Plus/localisation/000_CK2Plus_faction_events.csv
  CK2Plus/localisation/000_CK2Plus_factions.csv
  CK2Plus/localisation/000_CK2Plus_game_rules.csv
  CK2Plus/localisation/000_CK2Plus_governments.csv
  CK2Plus/localisation/000_CK2Plus_localisation_keys.csv
  CK2Plus/localisation/000_CK2Plus_maintenance_events.csv
  CK2Plus/localisation/000_CK2Plus_maintenance_traits.csv
  CK2Plus/localisation/000_CK2Plus_traits.csv
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_celtic_events.csv
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_laws.csv
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_overrides.csv
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_religions.csv
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_retinues.csv
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_societies.csv
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_tooltips.csv
  CK2Plus_expanded/localisation/000_CK2Plus_expanded_traits.csv
  CK2Plus_expanded/localisation/000_ck2Plus_expanded_titles.csv
Labels: enhancement

#137 removed expensive any_character
  CK2Plus/events/000_CK2Plus_maintenance_events.txt
Labels: enhancement

#143 Core: Death of Nations
  CK2Plus/common/on_actions/000_CK2Plus_on_actions.txt
  CK2Plus/events/000_CK2Plus_nation_death.txt
Labels: enhancement

#148 make lucia of sardinia female
  CK2Plus_expanded/history/characters/sardinian.txt
Labels: bug

#147 make shetland celtic pagan
  CK2Plus_expanded/history/characters/pictish.txt
  CK2Plus_expanded/history/provinces/33 - Faereyar.txt
  CK2Plus_expanded/history/provinces/34 - Shetland.txt
Labels: enhancement

#145 new kingdoms added
  CK2Plus_expanded/common/landed_titles/000_CK2Plus_expanded_landed_titles.txt
  CK2Plus_expanded/gfx/flags/k_algiers.tga
  CK2Plus_expanded/gfx/flags/k_azerbaijan.tga
  CK2Plus_expanded/gfx/flags/k_oman.tga
  CK2Plus_expanded/history/titles/d_alger.txt
  CK2Plus_expanded/history/titles/d_azerbaijan.txt
  CK2Plus_expanded/history/titles/d_kabylia.txt
  CK2Plus_expanded/history/titles/d_mzab.txt
  CK2Plus_expanded/history/titles/d_oman.txt
  CK2Plus_expanded/history/titles/d_tabriz.txt
  CK2Plus_expanded/history/titles/d_tahert.txt
  CK2Plus_expanded/localisation/000_ck2Plus_expanded_titles.csv
Labels: enhancement

#151 Titles/asia minor
  CK2Plus_expanded/history/titles/c_ani.txt
  CK2Plus_expanded/history/titles/c_lori.txt
  CK2Plus_expanded/history/titles/d_abydos.txt
  CK2Plus_expanded/history/titles/d_armenia_minor.txt
  CK2Plus_expanded/history/titles/d_cephalonia.txt
  CK2Plus_expanded/history/titles/d_cyprus.txt
  CK2Plus_expanded/history/titles/d_dyrrachion.txt
  CK2Plus_expanded/history/titles/d_epirus.txt
  CK2Plus_expanded/history/titles/d_erzerum.txt
  CK2Plus_expanded/history/titles/d_ohrid.txt
  CK2Plus_expanded/history/titles/d_optimatoi.txt
  CK2Plus_expanded/localisation/000_ck2Plus_expanded_titles.csv
Labels: enhancement

#154 Merge more-random-dynasties back into Master - also merge conflicts test
  CK2Plus_expanded/common/cultures/000_CK2Plus_amazigh.txt
  CK2Plus_expanded/common/cultures/000_CK2Plus_iranian.txt
  CK2Plus_expanded/common/cultures/000_CK2Plus_west_african.txt
  CK2Plus_expanded/common/dynasties/000_CK2Plus_expanded_dynasties_guanche.txt
  CK2Plus_expanded/common/dynasties/000_CK2Plus_expanded_dynasties_luri.txt
  CK2Plus_expanded/common/dynasties/000_CK2Plus_expanded_dynasties_szekely.txt
  CK2Plus_expanded/common/dynasties/000_CK2Plus_expanded_dynasties_wolof.txt
  CK2Plus_expanded/common/dynasties/00_dynasties.txt
Labels: CAUTION
