Repository ck2plus/CK2Plus_Rewrite, pull requests merged in 2019-12, with the labels that each got.

#155 Irish History Corrected
  CK2Plus_expanded/common/landed_titles/000_CK2Plus_expanded_landed_titles.txt
  CK2Plus_expanded/common/landed_titles/landed_titles.txt
  CK2Plus_expanded/gfx/flags/c_meath.tga
  CK2Plus_expanded/gfx/flags/d_meath.tga
  CK2Plus_expanded/gfx/flags/k_norman_ireland.tga
  CK2Plus_expanded/history/titles/c_breifne.txt
  CK2Plus_expanded/history/titles/c_desmond.txt
  CK2Plus_expanded/history/titles/c_hy_many.txt
  CK2Plus_expanded/history/titles/c_iarmond.txt
  CK2Plus_expanded/history/titles/c_leinster.txt
  CK2Plus_expanded/history/titles/c_leix.txt
  CK2Plus_expanded/history/titles/c_oriel.txt
  CK2Plus_expanded/history/titles/c_ormond.txt
  CK2Plus_expanded/history/titles/c_ossory.txt
  CK2Plus_expanded/history/titles/c_thomond.txt
  CK2Plus_expanded/history/titles/c_tyrconnell.txt
  CK2Plus_expanded/history/titles/c_ui_fiachrach.txt
  CK2Plus_expanded/history/titles/d_connacht.txt
  CK2Plus_expanded/history/titles/d_leinster.txt
  CK2Plus_expanded/history/titles/d_meath.txt
  CK2Plus_expanded/history/titles/d_munster.txt
  CK2Plus_expanded/history/titles/d_ulster.txt
  CK2Plus_expanded/history/titles/k_ireland.txt
  CK2Plus_expanded/history/titles/k_norman_ireland.txt
  CK2Plus_expanded/localisation/000_ck2Plus_expanded_titles.csv
Labels: enhancement

#156 Make Boats Necessary
  CK2Plus_expanded/map/adjacencies.csv
  CK2Plus_expanded/map/continent.txt
  CK2Plus_expanded/map/geographical_region.txt
  CK2Plus_expanded/map/island_region.txt
Labels: enhancement

#160 Berber GFX
  CK2Plus_expanded/gfx/flags/coa_head_berber.tga
  CK2Plus_expanded/gfx/flags/coa_order_berber.tga
  CK2Plus_expanded/gfx/interface/religion_icon_strip.dds
  CK2Plus_expanded/gfx/interface/religion_icon_strip_big.dds
  CK2Plus_expanded/gfx/interface/religion_icon_strip_small.dds
  CK2Plus_expanded/gfx/interface/societies/society_bg_warrior_berber.dds
  CK2Plus_expanded/gfx/interface/societies/society_icon_warrior_berber.dds
  CK2Plus_expanded/gfx/traits/trait_bad_priest_berber.dds
  CK2Plus_expanded/gfx/traits/trait_crusader_berber.dds
  CK2Plus_expanded/gfx/traits/trait_leader_berber.dds
Labels: enhancement

#165 some more minor fixes to religious stuff i noticed
  CK2Plus_expanded/common/societies/000_CK2Plus_expanded_societies.txt
  CK2Plus_expanded/common/traits/000_CK2Plus_expanded_traits.txt
Labels: bug

#166 Cultures/divide norse
  CK2Plus_expanded/history/characters/norse.txt
Labels: enhancement

#170 Island Hopping
  CK2Plus_expanded/map/island_region.txt
Labels: bug

#171 FIX: Stranded islanders
  CK2Plus/common/buildings/000_island_ships.txt
  CK2Plus/localisation/000_CK2Plus_buildings.csv
  CK2Plus_expanded/map/island_region.txt
Labels: bug, enhancement

#172 Really Big Walls
  CK2Plus/common/wonders/000_CK2Plus_wonders.txt
  CK2Plus/localisation/000_CK2Plus_wonders.csv
  CK2Plus_expanded/history/provinces/264 - Slesvig.txt
  CK2Plus_expanded/history/provinces/52 - Northumberland.txt
  CK2Plus_expanded/history/provinces/53 - Cumberland.txt
Labels: enhancement

#173 Oversight Correction
  CK2Plus/common/defines/000_CK2Plus_defines.lua
  CK2Plus/localisation/000_CK2Plus_wonders.csv
  CK2Plus_expanded/history/provinces/1687 - Lolland.txt
  CK2Plus_expanded/history/provinces/265 - Fyn.txt
  CK2Plus_expanded/history/provinces/266 - Sjaelland.txt
  CK2Plus_expanded/history/provinces/301 - Gotland.txt
Labels: enhancement

#174 Update Religion Icon Strip
  CK2Plus_expanded/gfx/flags/d_norse_pagan_reformed.tga
  CK2Plus_expanded/gfx/interface/religion_icon_strip.dds
  CK2Plus_expanded/gfx/interface/religion_icon_strip_big.dds
  CK2Plus_expanded/gfx/interface/religion_icon_strip_small.dds
  CK2Plus_expanded/interface/zzz_CK2Plus_overrides.gfx
Labels: bug

#176 add game rule for death of nations
  CK2Plus/common/game_rules/000_CK2Plus_game_rules.txt
  CK2Plus/events/000_CK2Plus_nation_death.txt
  CK2Plus/localisation/000_CK2Plus_game_rules.csv
Labels: enhancement

#179 localisation fixes for game rule
  CK2Plus/localisation/000_CK2Plus_game_rules.csv
Labels: bug

#180 Government Change to Feudal on Succession Fix
  CK2Plus/common/governments/nomadic_governments.txt
  CK2Plus/common/governments/tribal_governments.txt
Labels: bug, enhancement

#181 Governments correction
  CK2Plus/common/governments/feudal_governments.txt
  CK2Plus/common/governments/republic_governments.txt
  CK2Plus/common/governments/theocracy_governments.txt
Labels: bug

#169 cornish and cumbric added
  CK2Plus_expanded/history/characters/breton.txt
  CK2Plus_expanded/history/characters/welsh.txt
Labels: enhancement

#184 Nuristani: Kafiri
  CK2Plus_expanded/common/cultures/000_CK2Plus_nuristani.txt
  CK2Plus_expanded/common/dynasties/000_CK2Plus_expanded_dynasties_kafiri.txt
Labels: enhancement, question

#167 Make barons local
  CK2Plus_expanded/common/on_actions/000_CK2Plus_expanded_on_actions.txt
  CK2Plus_expanded/events/000_CK2Plus_startup_events.txt.txt
Labels: enhancement

#161 Persia
  CK2Plus_expanded/common/landed_titles/000_CK2Plus_expanded_landed_titles.txt
  CK2Plus_expanded/gfx/flags/k_chupanid.tga
  CK2Plus_expanded/gfx/flags/k_injuid.tga
  CK2Plus_expanded/gfx/flags/k_jalayarid.tga
  CK2Plus_expanded/history/titles/c_kara-kum.txt
  CK2Plus_expanded/history/titles/c_koloneia.txt
  CK2Plus_expanded/history/titles/c_lut.txt
  CK2Plus_expanded/history/titles/c_nishapur.txt
  CK2Plus_expanded/history/titles/c_oromieh.txt
  CK2Plus_expanded/history/titles/c_qazwin.txt
  CK2Plus_expanded/history/titles/c_qohistan.txt
  CK2Plus_expanded/history/titles/c_qom.txt
  CK2Plus_expanded/history/titles/c_rayy.txt
  CK2Plus_expanded/history/titles/c_tus.txt
  CK2Plus_expanded/history/titles/d_jibal.txt
  CK2Plus_expanded/history/titles/k_chupanid.txt
  CK2Plus_expanded/history/titles/k_injuid.txt
  CK2Plus_expanded/history/titles/k_jalayarid.txt
  CK2Plus_expanded/localisation/000_ck2Plus_expanded_titles.csv
Labels: enhancement

#186 germans done
  CK2Plus_expanded/history/characters/german.txt
  CK2Plus_expanded/history/characters/old_frankish.txt
Labels: enhancement

#188 Lombard (Italian) and Longobard (Germanic) switched
  CK2Plus_expanded/common/cultures/000_CK2Plus_italian.txt
  CK2Plus_expanded/common/dynasties/00_dynasties.txt
  CK2Plus_expanded/history/characters/lombard.txt
Labels: enhancement

#187 more fixes
  CK2Plus_expanded/history/titles/c_daylam.txt
  CK2Plus_expanded/history/titles/c_gilan.txt
  CK2Plus_expanded/history/titles/c_istakhr.txt
  CK2Plus_expanded/history/titles/c_nisibin.txt
  CK2Plus_expanded/history/titles/c_vaspurakan.txt
  CK2Plus_expanded/history/titles/e_il-khanate.txt
  CK2Plus_expanded/localisation/000_ck2Plus_expanded_titles.csv
Labels: enhancement

#189 Cb rework
  CK2Plus/common/cb_types/00_cb_types.txt
  CK2Plus/common/cb_types/01_cb_types.txt
  CK2Plus/common/cb_types/02_cb_types_shattered_world.txt
  CK2Plus/common/scripted_score_values/000_CK2Plus_scripted_score_values.txt
  CK2Plus/common/scripted_triggers/000_CK2Plus_scripted_triggers.txt
Labels: enhancement

#192 History/scandinavian balance
  CK2Plus/common/tributary_types/000_CK2Plus_tributary_types.txt
  CK2Plus/common/wonders/000_CK2Plus_wonders.txt
  CK2Plus/localisation/000_CK2Plus_localisation_keys.csv
  CK2Plus_expanded/history/technology/scandinavia.txt
  CK2Plus_expanded/history/titles/d_angria.txt
  CK2Plus_expanded/history/titles/d_holstein.txt
  CK2Plus_expanded/history/titles/d_saxony.txt
Labels: enhancement

#191 Religion icon strips re-organised
  CK2Plus_expanded/common/alternate_start/00_settings.txt
  CK2Plus_expanded/common/alternate_start/01_spread.txt
  CK2Plus_expanded/common/alternate_start/_documentation.info
Labels: enhancement

#193 Removed four remaining straits
  CK2Plus_expanded/map/adjacencies.csv
  CK2Plus_expanded/map/island_region.txt
Labels: bug, enhancement

#196 Cultures/divide italian
  CK2Plus_expanded/history/characters/italian.txt
Labels: enhancement

#199 Got converted to the wrong format at some point. This fixes it.
  CK2Plus_expanded/map/adjacencies.csv
Labels: bug

#205 Forgot to update the .mod file's overrides
  CK2Plus.mod
Labels: bug

#213 Cultures/castillan
  CK2Plus/history/characters/castillan.txt
  CK2Plus/history/characters/portuguese.txt
Labels: enhancement

#216 turkish and oghuz added
  CK2Plus/history/characters/turkish.txt
Labels: enhancement

#218 stuff changed
  CK2Plus/history/characters/russian.txt
Labels: enhancement
